Repository spryker/event-behavior, pull requests merged in 2019-10, with the labels that each got.

#39 TE-4300 Level 5 - rest of modules
  phpstan.json
  phpstan.neon
  src/Spryker/Zed/EventBehavior/Business/EventBehaviorFacade.php
  src/Spryker/Zed/EventBehavior/Business/EventBehaviorFacadeInterface.php
  src/Spryker/Zed/EventBehavior/Business/Model/EventResourcePluginResolver.php
  src/Spryker/Zed/EventBehavior/Communication/Console/EventBehaviorTriggerTimeoutConsole.php
  src/Spryker/Zed/EventBehavior/Communication/Console/EventTriggerConsole.php
  src/Spryker/Zed/EventBehavior/Dependency/Service/EventBehaviorToUtilEncodingBridge.php
  src/Spryker/Zed/EventBehavior/Dependency/Service/EventBehaviorToUtilEncodingInterface.php
  src/Spryker/Zed/EventBehavior/Persistence/EventBehaviorQueryContainer.php
  src/Spryker/Zed/EventBehavior/Persistence/EventBehaviorQueryContainerInterface.php
  src/Spryker/Zed/EventBehavior/Persistence/Propel/AbstractSpyEventBehaviorEntityChange.php
  src/Spryker/Zed/EventBehavior/Persistence/Propel/AbstractSpyEventBehaviorEntityChangeQuery.php
  tests/SprykerTest/Zed/EventBehavior/Business/EventBehaviorFacadeTest.php
  tests/SprykerTest/Zed/EventBehavior/Business/Model/EventResourceQueryContainerManagerTest.php
  tests/SprykerTest/Zed/EventBehavior/_support/EventBehaviorBusinessTester.php
Labels: improvement, merge-only, ready-for-release

#38 TE-4081 added transaction to read of state and process from DB
  src/Spryker/Zed/EventBehavior/Persistence/Propel/Schema/spy_event_behavior.schema.xml
Labels: improvement, ready-for-release

#40 Fix transfer definition file names
  src/Spryker/Shared/EventBehavior/Transfer/event_behavior.transfer.xml
Labels: merge-only

#42 MP-1057: MP-1256: Created posibility for sending additional fields
  src/Spryker/Shared/EventBehavior/Transfer/event_behavior.transfer.xml
  src/Spryker/Zed/EventBehavior/Business/EventBehaviorFacade.php
  src/Spryker/Zed/EventBehavior/Business/EventBehaviorFacadeInterface.php
  src/Spryker/Zed/EventBehavior/Business/Model/EventEntityTransferFilter.php
  src/Spryker/Zed/EventBehavior/Business/Model/EventEntityTransferFilterInterface.php
  src/Spryker/Zed/EventBehavior/Business/Model/TriggerManager.php
  src/Spryker/Zed/EventBehavior/Persistence/Propel/Behavior/EventBehavior.php
  tests/SprykerTest/Zed/EventBehavior/Business/EventBehaviorFacadeTest.php
Labels: ready-for-release
