Repository spryker/event-behavior, pull requests merged in 2020-10, with the labels that each got.

#53 TE-7001 Updated Symfony console commands to always return int.
  src/Spryker/Zed/EventBehavior/Communication/Console/EventBehaviorTriggerTimeoutConsole.php
  src/Spryker/Zed/EventBehavior/Communication/Console/EventTriggerConsole.php
  src/Spryker/Zed/EventBehavior/Communication/Console/EventTriggerListenerConsole.php
Labels: improvement, ready-for-release

#55 TE-7611 Fixed dependencies.
  composer.json
Labels: merge-only, ready-for-release

#56 TE-7780 Fix console return type and PHPStan level 7.
  .travis.yml
  composer.json
  phpstan.json
  phpstan.neon
  psalm-report.json
  src/Spryker/Zed/EventBehavior/Business/EventBehaviorFacade.php
  src/Spryker/Zed/EventBehavior/Business/EventBehaviorFacadeInterface.php
  src/Spryker/Zed/EventBehavior/Business/Model/EventEntityTransferFilterInterface.php
  src/Spryker/Zed/EventBehavior/Business/Model/EventResourceManagerInterface.php
  src/Spryker/Zed/EventBehavior/Business/Model/EventResourcePluginResolver.php
  src/Spryker/Zed/EventBehavior/Business/Model/EventResourcePluginResolverInterface.php
  src/Spryker/Zed/EventBehavior/Business/Model/EventResourceQueryContainerManager.php
  src/Spryker/Zed/EventBehavior/Business/Model/EventResourceRepositoryManager.php
  src/Spryker/Zed/EventBehavior/Business/Model/TriggerManager.php
  src/Spryker/Zed/EventBehavior/Communication/Console/EventTriggerConsole.php
  src/Spryker/Zed/EventBehavior/Communication/Console/EventTriggerListenerConsole.php
  src/Spryker/Zed/EventBehavior/Dependency/Facade/EventBehaviorToEventBridge.php
  src/Spryker/Zed/EventBehavior/Dependency/Facade/EventBehaviorToEventInterface.php
  src/Spryker/Zed/EventBehavior/Dependency/Plugin/EventResourceQueryContainerPluginInterface.php
  src/Spryker/Zed/EventBehavior/Dependency/Plugin/EventResourceRepositoryPluginInterface.php
  src/Spryker/Zed/EventBehavior/Persistence/EventBehaviorQueryContainer.php
  tests/SprykerTest/Zed/EventBehavior/_support/EventBehaviorBusinessTester.php
Labels: bug, prio, ready-for-release
